parameters:
  - name: PENSION_DASHBOARD_URL
    type: string
    default: ''

  - name: MHPD_API_DOMAIN
    type: string
    default: ''

  - name: REDIRECT_TEST_URL
    type: string
    default: ''

jobs:
  - job: AccessibilityTests
    displayName: 'Run Accessibility Tests'
    dependsOn: ${{ parameters.dependsOnJob }}
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'workspace'
          targetPath: '$(System.DefaultWorkingDirectory)/tests'
        displayName: 'Download Workspace Artifact'

      - task: CmdLine@2
        inputs:
          script: |
            chmod -R 755 $(System.DefaultWorkingDirectory)
            chmod +x ./node_modules/.bin/playwright
        displayName: 'Fix Permissions for directory'

      - task: CmdLine@2
        inputs:
          script: |
            npx playwright install &&
            npx playwright test --grep @accessibility --project=chromium
        env:
          PENSION_DASHBOARD_URL: ${{ parameters.REDIRECT_TEST_URL }}
          PASSWORD: $(PASSWORD)
          pension-dashboard-password: $(pension-dashboard-password)
          MHPD_API_DOMAIN: ${{ parameters.MHPD_API_DOMAIN }}
          api-test-ticket: $(api-test-ticket)
          REDIRECT_TEST_URL: ${{ parameters.REDIRECT_TEST_URL }}
        displayName: 'Run Accessibility tests'
        continueOnError: true

      - task: PublishHtmlReport@1
        displayName: 'Accessibility Test HTML Results'
        inputs:
          htmlType: 'Axe-Core'
          reportDir: 'test-results'
          tabName: 'Accessibility Tests'
        condition: always()

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/**/result.xml'
          testRunTitle: 'MHPD Accessibility Tests'
        displayName: 'Publish Accessibility Test Results'
