parameters:
  - name: PENSION_DASHBOARD_URL
    type: string
    default: ''

  - name: MHPD_API_DOMAIN
    type: string
    default: ''

  - name: REDIRECT_TEST_URL
    type: string
    default: ''

jobs:
  - job: APITests
    displayName: 'Run API Tests'
    dependsOn: ${{ parameters.dependsOnJob }}
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'workspace'
          targetPath: '$(System.DefaultWorkingDirectory)'
        displayName: 'Download Workspace Artifact'

      - task: CmdLine@2
        inputs:
          script: |
            npx playwright install &&
            npx playwright test --grep @api --project=chromium
        displayName: 'Run API tests'
        env:
          MHPD_API_DOMAIN: ${{ parameters.MHPD_API_DOMAIN }}
          api-test-ticket: $(api-test-ticket)
          REDIRECT_TEST_URL: ${{ parameters.REDIRECT_TEST_URL }}
          code-verifier: $(variables.code-verifier)
        continueOnError: true

      - task: PublishHtmlReport@1
        displayName: 'API Test HTML Results'
        inputs:
          htmlType: 'Playwright-HTML'
          reportDir: 'playwright-report'
          tabName: 'API tests'
        condition: always()

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: 'test-results/**/result.xml'
          testRunTitle: 'MHPD API Tests'
        displayName: 'Publish API Test Results'
