parameters:
  - name: notificationGroup
    type: string
    default: ''

jobs:
  - job: ManualApproval
    displayName: 'Approval Pending'
    steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: ${{ parameters.notificationGroup }}
          instructions: 'Please approve the deployment to proceed.'
          onTimeout: 'reject'
          timeout: '1d'
          continueOnError: false
        name: WaitForApproval