jobs:
  - job: incrementRevision
    displayName: "Increment API Revision"
    dependsOn: exportSpec
    variables:
      API_SPEC_UPDATED: $[ dependencies.exportSpec.outputs['setApiSpecUpdated.API_SPEC_UPDATED'] ]
    steps:

    - checkout: ado-templates
      path: ado-templates

    - script: |
        pwd
        ls
        ls ../
        echo "break"
        
        chmod +x $(Build.SourcesDirectory)/../ado-templates/pipeline-scripts/bump-revision.sh
        $(Build.SourcesDirectory)/../ado-templates/pipeline-scripts/bump-revision.sh
      displayName: "Increment API Revision"