jobs:
  - job: incrementRevision
    displayName: "Increment API Revision"
    dependsOn: exportSpec
    variables:
      API_SPEC_UPDATED: $[ dependencies.exportSpec.outputs['setApiSpecUpdated.API_SPEC_UPDATED'] ]
    steps:

    - checkout: ado-templates
      path: ado-templates

    - checkout: mhpd-backend-cda-service
      path: service-repo

        echo "Current directory:"
        pwd

        echo "Top-level directory:"
        ls -la $(Build.SourcesDirectory)

        echo "Changing to service-repo..."
        cd "$(Build.SourcesDirectory)/service-repo"
        echo "Contents of service-repo:"
        ls -la

        echo "break"

        chmod +x $(Build.SourcesDirectory)/../ado-templates/pipeline-scripts/bump-revision.sh
        $(Build.SourcesDirectory)/../ado-templates/pipeline-scripts/bump-revision.sh
      displayName: "Increment API Revision"
      env:
        SERVICE_NAME: ${{ parameters.scriptEnvVars.SERVICE_NAME }}
        COMPONENT: ${{ parameters.scriptEnvVars.COMPONENT }}
        TF_FILE: ${{ parameters.scriptEnvVars.TF_FILE }}
        AZURE_REPO: ${{ parameters.scriptEnvVars.AZURE_REPO }}
        SOURCE_PATH: ${{ parameters.scriptEnvVars.SOURCE_PATH }}