jobs:
  - job: FunctionalTests
    displayName: 'Run Functional Tests'
    dependsOn: ${{ parameters.dependsOnJob }}
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'workspace'
          targetPath: '$(System.DefaultWorkingDirectory)'
        displayName: 'Download Workspace Artifact'

      # - task: CmdLine@2
      #   inputs:
      #     script: |
      #       chmod -R 755 $(System.DefaultWorkingDirectory)
      #       chmod +x ./node_modules/.bin/playwright
      #   displayName: 'Fix Permissions for directory'

      - task: CmdLine@2
        inputs:
          script: |
            npx playwright install &&
            npx playwright test --grep @functional --project=chromium
        displayName: 'Run Functional tests'
        env:
          PENSION_DASHBOARD_URL: ${{ parameters.REDIRECT_TEST_URL }}
          pension-dashboard-password: $(pension-dashboard-password)
        continueOnError: true

      - task: PublishHtmlReport@1
        displayName: 'Functional Test HTML Results'
        inputs:
          htmlType: 'Playwright-HTML'
          reportDir: 'playwright-report'
          tabName: 'Functional tests'
        condition: always()

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: 'test-results/**/result.xml'
          testRunTitle: 'MHPD Functional Tests'
        displayName: 'Publish Functional Test Results'
