jobs:
  - job: PublishSpec
    displayName: 'Publish OpenAPI Spec'
    pool:
      vmImage: $(vmImageName)

    steps:
      - task: Checkout@1
        inputs:
          repository: 'https://github.com/moneyadviceservice/api-docs'
          persistCredentials: true
          path: 'specs'

      # - task: DotNetCoreCLI@2
      #   displayName: 'Generate OpenAPI Spec'
      #   inputs:
      #     command: 'custom'
      #     custom: 'swagger'
      #     arguments: 'tofile --output openapi.json ./bin/Release/net6.0/YourApi.dll v1'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish OpenAPI Spec as Artifact'
        inputs:
          targetPath: '$(Build.SourcesDirectory)/openapi.json'
          artifact: 'OpenAPI'

      - script: |
          cp openapi.json api-docs/
          cd api-docs
          git add openapi.json
          git commit -m "Update OpenAPI spec"
          git push origin main
        displayName: 'Commit OpenAPI Spec to api-docs Repo'