jobs:
  - job: exportSpec
    displayName: "Export API Spec"
    steps:
      - checkout: self
        fetchDepth: 2 

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'ADO-PWD-Connection'
          KeyVaultName:  ${{ parameters.scriptEnvVars.VAULT_NAME }}
          SecretsFilter: 'bot-azure-pat, bot-github-pat'

      - script: |
          echo "Current working directory:"
          pwd
          echo "Listing contents of parent directory:"
          ls ../
          chmod +x $(Build.SourcesDirectory)/../ado-templates/pipeline-scripts/sync-api-docs.sh
          $(Build.SourcesDirectory)/../ado-templates/pipeline-scripts/sync-api-docs.sh
        displayName: 'Export API Spec to api-docs repo'
        name: 'exportSpec'